export interface Service {
  id: string;
  slug: string;
  name: string;
  nameEn: string;
  tagline: string;
  description: string;
  category: string;
  target: string;
  targetAge: string[];
  features: string[];
  pros: string[];
  cons: string[];
  recommended: string[];
  affiliateUrl: string;
  ctaText: string;
  color: string;
}

export const services: Service[] = [
  {
    id: 'coconala-phone',
    slug: 'coconala-phone',
    name: 'ココナラ電話占い',
    nameEn: 'Coconala Phone Fortune',
    tagline: '実力派占い師に、今すぐ電話で相談できる',
    description: 'TVCM放映の大手サービス。初回最大30分無料で、恋愛に強い占い師が多数在籍。声を聞きながら安心して相談できます。',
    category: '電話占い',
    target: '声を聞いて安心したい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['初回最大30分無料で気軽にお試し', '恋愛相談に強い占い師が多数在籍', '24時間いつでも相談可能'],
    pros: ['初回無料特典が手厚い', '占い師のレビューが豊富で選びやすい'],
    cons: ['人気占い師は待ち時間あり'],
    recommended: ['すぐに誰かに話を聞いてほしい', '電話で直接相談したい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=3NN907+ASSJS2+2PEO+C4LLD',
    ctaText: '話を聞いてもらう',
    color: '#9b7ec8',
  },
  {
    id: 'miror',
    slug: 'miror',
    name: 'MIROR（ミラー）',
    nameEn: 'MIROR',
    tagline: '利用者50万人突破、2000人以上の占い師が在籍',
    description: '利用者数50万人を突破した人気の占いサービス。2000人以上の占い師から自分にぴったりの先生を見つけられます。恋愛相談の実績が豊富です。',
    category: 'チャット占い・電話占い',
    target: '自分に合う占い師を見つけたい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['利用者数50万人突破の実績', '占い師2000人以上から選べる', '恋愛相談の実績が豊富'],
    pros: ['占い師の選択肢が圧倒的に多い', '口コミで自分に合う先生が見つかる'],
    cons: ['選択肢が多く迷う場合も'],
    recommended: ['多くの占い師から選びたい', '口コミを参考にしたい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4JQP42+4PWE+5YJRM',
    ctaText: '話を聞いてもらう',
    color: '#c47ea8',
  },
  {
    id: 'coconala-mail',
    slug: 'coconala-mail',
    name: 'ココナラ占い＆お悩み相談',
    nameEn: 'Coconala Mail Fortune',
    tagline: '500円から、心に寄り添うメール占い',
    description: '電話が苦手でも大丈夫。文章でじっくり自分の気持ちを整理しながら相談できるメール占い。占い師だけでなくカウンセラーにも相談可能。',
    category: 'メール占い・チャット占い',
    target: '文章で気持ちを整理したい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['500円からの手頃な料金設定', '占い・カウンセリング両方に対応', '自分のペースで好きな時に相談'],
    pros: ['電話不要で気軽に相談できる', '料金がリーズナブル'],
    cons: ['リアルタイムの対話は難しい'],
    recommended: ['電話が苦手', 'まずは気軽に試してみたい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4HCYOY+2PEO+1BO6EQ',
    ctaText: '話を聞いてもらう',
    color: '#a87ec4',
  },
  {
    id: 'spacia',
    slug: 'spacia',
    name: '恋愛応援スペーシア',
    nameEn: 'Spacia',
    tagline: '当たると評判の霊感霊視で、あなたの恋を鑑定',
    description: '霊感霊視に特化した電話占い。恋愛の悩みに深く寄り添い、相手の気持ちや未来の行方を鑑定してくれます。当たると口コミで評判のサービスです。',
    category: '電話占い（霊感霊視）',
    target: 'スピリチュアルな鑑定を求める方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['霊感霊視に特化した占い師が在籍', '恋愛相談に強い実績', '当たると口コミで評判'],
    pros: ['霊感霊視で深い鑑定が受けられる', '恋愛特化で的確なアドバイス'],
    cons: ['占い師の数は大手より少なめ'],
    recommended: ['スピリチュアルな鑑定を受けたい', '相手の気持ちを深く知りたい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4IJTWI+3SKE+5YRHE',
    ctaText: '話を聞いてもらう',
    color: '#8e6bb5',
  },
  {
    id: 'brillante',
    slug: 'brillante',
    name: 'チャット占いブリランテ',
    nameEn: 'Brillante',
    tagline: 'チャットで気軽に、本格恋愛占い',
    description: 'テキストベースで気軽に相談できるチャット占い。深夜でも相談可能で、文字で記録が残るので占い師のアドバイスを何度でも読み返せます。',
    category: 'チャット占い',
    target: 'テキストで気軽に相談したい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['チャット形式で深夜でも相談可能', 'テキストで記録が残る', '気軽にスタートできる'],
    pros: ['時間を気にせず相談できる', '文字で記録が残り読み返せる'],
    cons: ['音声でのやり取りはなし'],
    recommended: ['深夜に相談したい', 'テキストのほうが話しやすい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4G63HE+5SGG+5YJRM',
    ctaText: '話を聞いてもらう',
    color: '#b87ec4',
  },
  {
    id: 'destiny',
    slug: 'destiny',
    name: '電話占いデスティニー',
    nameEn: 'Destiny Phone Fortune',
    tagline: '運命の相手を知りたいなら、デスティニーの電話占い',
    description: '的中率の高さで評判の電話占いサービス。恋愛・結婚・復縁など恋の悩みに特化した占い師が多数在籍。電話一本で本格鑑定が受けられます。',
    category: '電話占い',
    target: '恋愛の悩みを深く相談したい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['恋愛・結婚に特化した占い師が在籍', '的中率の高さで口コミ評判', '電話一本で本格鑑定'],
    pros: ['恋愛特化で的確なアドバイス', '実力派占い師が揃っている'],
    cons: ['電話のみの対応'],
    recommended: ['恋愛の悩みを深く相談したい', '的中率の高い占い師に相談したい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4FKNVM+1SZG+5ZEMQ',
    ctaText: '話を聞いてもらう',
    color: '#7e6bb5',
  },
  {
    id: 'raffine',
    slug: 'raffine',
    name: '電話占い・霊感占いラフィネ',
    nameEn: 'Raffine',
    tagline: '厳しい採用基準をクリアした本物の占い師が在籍',
    description: '厳格な審査を通過した実力派の霊感占い師だけが在籍。量より質にこだわり、本物の鑑定を求める方に選ばれている電話占いサービスです。',
    category: '電話占い（霊感占い）',
    target: '本物の占い師に相談したい方に',
    targetAge: ['20代', '30代', '40代'],
    features: ['厳しい採用基準をクリアした占い師のみ在籍', '霊感占いに特化した実力派揃い', '恋愛・復縁相談の実績が豊富'],
    pros: ['占い師の質が高く安心できる', '霊感占いで深い鑑定が受けられる'],
    cons: ['占い師の人数は大手より少なめ'],
    recommended: ['本物の霊感占い師に相談したい', '厳選された占い師に鑑定してほしい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4M4FJ6+4646+5YJRM',
    ctaText: '話を聞いてもらう',
    color: '#6b5b95',
  },
  {
    id: 'etoile',
    slug: 'etoile',
    name: '電話占い Etoile（エトワール）',
    nameEn: 'Etoile',
    tagline: 'トップクラスの鑑定師が名を連ねる至高の電話占い',
    description: '業界トップクラスの実力派鑑定師だけが在籍する、ワンランク上の電話占いサービス。恋愛・復縁・不倫など複雑な恋の悩みに、精度の高い鑑定で的確なアドバイスを提供します。',
    category: '電話占い（プレミアム）',
    target: '最高品質の鑑定を求める方に',
    targetAge: ['20代', '30代', '40代', '50代'],
    features: ['トップクラスの鑑定師のみ厳選在籍', '恋愛・復縁の複雑な悩みに強い', '精度の高い本格鑑定'],
    pros: ['鑑定師の質が業界最高レベル', '複雑な恋愛相談に的確な回答'],
    cons: ['一般的な電話占いより料金が高め'],
    recommended: ['最高品質の鑑定を受けたい', '複雑な恋の悩みを抱えている'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+403E5E+48YY+HV7V6',
    ctaText: '話を聞いてもらう',
    color: '#d4af37',
  },
  {
    id: 'ulana',
    slug: 'ulana',
    name: '電話占い・メール占いULana（ウラナ）',
    nameEn: 'ULana',
    tagline: '初回10分無料、実力派占い師に今すぐ相談',
    description: '電話占い・メール占いの両方に対応した総合占いサービス。初回10分無料で、恋愛・復縁・不倫など複雑な悩みに寄り添う実力派占い師が多数在籍しています。',
    category: '電話占い・メール占い',
    target: '電話でもメールでも相談したい方に',
    targetAge: ['20代', '30代', '40代', '50代'],
    features: ['初回10分無料で気軽にお試し', '電話占い・メール占い両対応', '恋愛・復縁に強い占い師が在籍'],
    pros: ['電話とメールの両方が選べて便利', '初回無料特典で試しやすい'],
    cons: ['知名度は大手より低め'],
    recommended: ['電話もメールも使い分けたい', '複雑な恋の悩みを相談したい'],
    affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZHWA+4GRJ36+2VYS+61JSI',
    ctaText: '話を聞いてもらう',
    color: '#e88ca5',
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
